### ISSUE TITLE
The return value of "from_path" doesn't match the comments in the function

### ISSUE THREAD

**Issue by juzen2003** [SETI/rms-webtools#24]
- Current from_path expected results based on comments:
  - 'COISS_2001.targz' --> 'archives-volumes/COISS_2xxx/COISS_2001.tar.gz'
  - 'COISS_2001_previews.targz' --> 'archives-previews/COISS_2xxx/COISS_2001_previews.tar.gz'
  - 'COISS_0xxx_tar.gz' -->  'archives-volumes/COISS_2xxx'

- Actual return results from function:
  - 'COISS_2001.targz' --> previews/COISS_2xxx/COISS_2001
  - 'COISS_2001_previews.targz' --> volumes/COISS_2xxx/COISS_2001
  - 'COISS_0xxx_tar.gz' --> 'volumes/COISS_0xxx'

**Comment by rfrenchseti** [comment]
Is this still a problem? All the tests are passing.
