### ISSUE TITLE
Code coverage shows potential bugs/missing items in tests

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-webtools#52]
- rules/COCIRS_xxx.py never executes the loop at 1108 or the if at 1116.
- rules/COUVIS_0xxx.py doesn't exercise various branches in DATA_SET_ID()
- rules/COVIMS_0xxx.py doesn't exercise various branches in OPUS_ID_TO_PRIMARY_LOGICAL_PATH()
- filename_keylen is never tested
- tests/test_pdsfile_blackbox.py The clause at line 1271 is never executed
- tests/test_pdsfile_blackbox.py The loop at line 3042 never starts
- tests/test_pdsfile_whitebox.py The loop at 877 never starts

**Comment by matthewtiscareno** [comment]
Please clarify which is new:  the bug, or the test revealing the bug.

**Comment by rfrenchseti** [comment]
Neither. There are no new tests - this is a bug report on existing code. The bugs aren't new - they've been there for a long time. I just noticed them with code coverage analysis.

Code coverage has shown that certain parts of the test suite are not being executed. This shows a bug or deficiency in the test suite itself, since test suites should always run at 100%. However, the problems with the test suite may hide detection of actual bugs in the code. Dave, who understands both the code and the tests, needs to figure out which is true in each case.

I am not yet aware of new bugs in the code being tested at this point.
