### ISSUE TITLE
Accommodation for pds4file, convert `is_volume` & `is_volume_dir`

### ISSUE THREAD

**Issue by juzen2003** [SETI/rms-webtools#64]
- Use `Pds4FileTest/pds4/bundles` as an example, the pds3 volume level should be the `uranus_occ_u0_kao_91cm` in our pds4 bundle `uranus_occs_earthbased` directory.

**Comment by matthewtiscareno** [comment]
I agree that `uranus_occ_u0_kao_91cm` is one example of the PDS4 equivalent of what we called a "volume" in PDS3.
