### ISSUE TITLE
Accommodation for pds4file, convert `is_volset` & `is_volset_dir` & `volset`

### ISSUE THREAD

**Issue by juzen2003** [SETI/rms-webtools#65]
- Use `Pds4FileTest/pds4/bundles` as an example, the pds3 volset level should be the `uranus_occs_earthbased` in our pds4 `bundles` directory.

**Comment by mace-space** [comment]
The modifications for #59 seem to accomodate `is_volset`, `is_volset_dir`, and `volset`
