### ISSUE TITLE
Accommodation for pds4file, use snake case for naming

### ISSUE THREAD

**Issue by juzen2003** [SETI/rms-webtools#70]
- Clean up to make sure naming are consistent in the repo, we use snake case (replace white space with "_") in the naming for python code in the repo, so we can do something like ```Pds4_File``` instead of camel case ```Pds4File``` to make it consistent.

**Comment by rfrenchseti** [comment]
I'm not quite understanding this. We should use CamelCase for class names (Pds4File) and all-lower-case-with-underscores for everything else. We should never mix capitalization with underscores, so `Pds4_File` shouldn't be an option. It's either `Pds4File` or `pds4_file`.

**Comment by matthewtiscareno** [comment]
For the currently existing code, filenames are lowercase (e.g., `pdsfile.py`) and references in text are CamelCase (e.g., PdsFile).  I've been assuming we would correspondingly use `pds4file.py` and Pds4File.

**Comment by rfrenchseti** [comment]
Oh, I see you're talking about the actual filenames in the repo. Yes I agree `pds4file.py` is what I was assuming as well.
